// Spec++ in a Playwright config: scenarios become ordinary Playwright tests,
// so Playwright's command line, UI mode, reports and editor extensions work on
// them as they do on any test.
//
//     // playwright.config.ts
//     import { defineConfig } from '@playwright/test'
//     import { defineSppConfig } from 'spp-lang'
//
//     export default defineConfig({
//       ...defineSppConfig({ features: ['features'] }),
//       use: { baseURL: 'http://localhost:3000' },
//     })
//
// defineSppConfig writes a test file for each .spp file, and each Markdown
// file with an ```spp block, into its outputDir, and returns the testDir and
// testMatch that find them. The testDir is the project's root, not the
// outputDir, so Playwright says where tests are relative to the root:
// features/cart.spp, not ../features/cart.spp.
//
// The files are written every time Playwright loads the config, so they're
// never out of date, and they're no more than a list of the scenarios: what
// each one does is read from the .spp file when it runs (runtime.ts). Each has
// a source map back to its .spp file, so Playwright puts every test, and every
// failure, on its line in the .spp file.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import type { Project } from '../../config.ts'
import { registry } from '../../config.ts'
import { check } from '../../language/check.ts'
import { core } from '../../language/cognate.ts'
import type { Feature, Scenario, SppFile } from '../../language/load.ts'
import { discover, LoadError, load } from '../../language/load.ts'
import { escapeRegExp, leftovers } from '../../words/shared.ts'
import { browser } from './words.ts'

export interface SppConfig {
  // Where the .spp files are. By default, everywhere under the root.
  features?: string[]
  // Files and directories to leave out, like fixtures that are meant to fail.
  ignore?: string[]
  // Where the generated tests go, for testDir. By default, .spp-tests. Each
  // defineSppConfig in a config needs its own.
  outputDir?: string
  // What the paths are relative to. By default, the directory of the config
  // that calls defineSppConfig, as Playwright's own paths are.
  root?: string
}

// What a Playwright config, or one of its projects, needs to run the
// generated tests. An explicit testDir also means Playwright doesn't leave out
// what .gitignore does, so .spp-tests can be ignored.
export interface SppTests {
  testDir: string
  testMatch: RegExp
}

export function defineSppConfig(config: SppConfig = {}): SppTests {
  const root = path.resolve(config.root ?? callerDir())
  const strings = (paths: string[] | undefined, what: string) => {
    if (paths !== undefined && !(Array.isArray(paths) && paths.every((p) => typeof p === 'string'))) {
      throw new Error(`defineSppConfig: ${what} should be a list of paths`)
    }
    return (paths ?? []).map((p) => path.resolve(root, p))
  }
  const features = strings(config.features, 'features')
  const project: Project = {
    root,
    features: features.length ? features : [root],
    ignore: strings(config.ignore, 'ignore'),
    outputDir: path.resolve(root, config.outputDir ?? '.spp-tests'),
  }
  registry.projects.push(project)
  // Playwright loads the config in every worker too, but only its first load,
  // in the main process, should write anything.
  if (!registry.collecting && process.env.TEST_WORKER_INDEX === undefined) generate(project)
  return { testDir: root, testMatch: new RegExp(`^${escapeRegExp(project.outputDir + path.sep)}.*\\.spec\\.js$`) }
}

// The directory of the file that called defineSppConfig: the config. Read
// from the stack, as Playwright reads where each test is declared.
function callerDir(): string {
  const prepare = Error.prepareStackTrace
  let caller: string | null | undefined
  try {
    Error.prepareStackTrace = (_err, frames) => {
      caller = frames[0]?.getFileName()
      return ''
    }
    const holder: { stack?: string } = {}
    Error.captureStackTrace(holder, defineSppConfig)
    // Reading the stack is what runs prepareStackTrace.
    if (holder.stack === undefined) caller = undefined
  } finally {
    Error.prepareStackTrace = prepare
  }
  if (!caller) throw new Error("defineSppConfig couldn't tell which file called it. Give it a root.")
  return path.dirname(caller.startsWith('file:') ? fileURLToPath(caller) : caller)
}

// ---------------------------------------------------------------- generating

const HEADER = '// Generated by Spec++'

// .ts when run from source, .js once built.
const RUNTIME = path.join(import.meta.dirname, `runtime${path.extname(import.meta.filename)}`)

// Writes a test file for each file in the project that has scenarios or
// mistakes, and removes those for files that no longer do. A file is only
// written when it changes, so watchers don't see a change on every run.
export function generate(project: Project): string[] {
  const files: SppFile[] = []
  const broken = new Map<string, LoadError>()
  for (const file of discover(project.features, project.root, project.ignore)) {
    try {
      files.push(load(file))
    } catch (err) {
      if (!(err instanceof LoadError)) throw err
      broken.set(file, err)
    }
  }
  const report = check(files, { words: browser(core()), settle: leftovers, cwd: project.root })

  const written = new Set<string>()
  const write = (source: string, test: GeneratedTest) => {
    const out = path.join(project.outputDir, `${path.relative(project.root, source)}.spec.js`)
    fs.mkdirSync(path.dirname(out), { recursive: true })
    const { code, map } = render(project, source, out, test)
    for (const [file, text] of [
      [out, code],
      [`${out}.map`, map],
    ]) {
      if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text) fs.writeFileSync(file, text)
      written.add(file)
    }
  }

  for (const { file, features } of files) {
    const defines = report.vocabulary.filter((d) => d.file === file)
    const mistakes = new Set(features.flatMap((f) => f.scenarios).filter((s) => report.scenarios.has(s)))
    if (features.some((f) => f.scenarios.length) || defines.length) write(file, { features, defines, mistakes })
  }
  for (const [file, err] of broken) write(file, { features: [], defines: [], broken: err })

  // ESM whatever the project's own package.json says.
  const pkg = path.join(project.outputDir, 'package.json')
  fs.mkdirSync(project.outputDir, { recursive: true })
  if (!fs.existsSync(pkg)) fs.writeFileSync(pkg, '{ "type": "module" }\n')
  removeStale(project.outputDir, written)
  return [...written]
}

interface GeneratedTest {
  features: Feature[]
  // the scenarios the checker found a mistake in, which fail without a browser
  mistakes?: Set<Scenario>
  defines: { line: number; define?: string }[]
  broken?: LoadError
}

// A generated file, line by line, each line with the line of the source it
// stands for, if any.
type Lines = [string, number | undefined][]

// The file, and its source map, which is a file of its own: Playwright reads
// either kind, but its VS Code extension only reads a map in a file, and needs
// one to know that the tests are the .spp file's.
function render(
  project: Project,
  source: string,
  out: string,
  { features, defines, mistakes, broken }: GeneratedTest,
): { code: string; map: string } {
  const s = (value: unknown) => JSON.stringify(value)
  const lines: Lines = [
    [
      `${HEADER} from ${path.relative(project.root, source)}, each time Playwright loads its config. Don't edit it.`,
      undefined,
    ],
    [`import { project } from ${s(pathToFileURL(RUNTIME).href)}`, undefined],
    [`const { test, scenario, mistake, define, broken } = project(${s(project)})`, undefined],
    [`const file = ${s(source)}`, undefined],
  ]

  if (broken) {
    lines.push([`test(${s(path.basename(source))}, broken(file))`, broken.problems[0]?.line ?? 1])
  }
  // One test per broken Define, as there's one per scenario.
  const seen = new Set<number>()
  for (const d of defines) {
    if (seen.has(d.line)) continue
    seen.add(d.line)
    lines.push([`test(${s(d.define ? `Define ${d.define}` : 'Defines')}, define(file, ${d.line}))`, d.line])
  }

  for (const feature of features) {
    if (!feature.scenarios.length) continue
    lines.push([`test.describe(${s(feature.name || path.basename(source))}, () => {`, feature.line])
    // An Outline's rows go together, under it. open is the line of the
    // Outline whose describe is open.
    let open: number | undefined
    for (const scenario of feature.scenarios) {
      const { outline } = scenario
      if (open !== undefined && outline?.line !== open) {
        lines.push(['  })', undefined])
        open = undefined
      }
      if (outline && open === undefined) {
        lines.push([`  test.describe(${s(outline.name)}, () => {`, outline.line])
        open = outline.line
      }
      const indent = outline ? '    ' : '  '
      lines.push([`${indent}${declaration(scenario, mistakes?.has(scenario) ?? false)}`, scenario.line])
    }
    if (open !== undefined) lines.push(['  })', undefined])
    lines.push(['})', undefined])
  }

  const code = `${lines.map(([line]) => line).join('\n')}\n//# sourceMappingURL=${path.basename(out)}.map\n`
  return { code, map: sourceMap(path.relative(path.dirname(out), source), lines) }
}

function declaration(scenario: Scenario, mistaken: boolean): string {
  const s = (value: unknown) => JSON.stringify(value)
  const title = scenario.outline ? scenario.outline.row : scenario.name
  const declare = scenario.tags.includes('@only') ? 'test.only' : 'test'
  const details = scenario.tags.length ? `{ tag: ${s(scenario.tags)} }, ` : ''
  const body = mistaken ? 'mistake' : 'scenario'
  return `${declare}(${s(title)}, ${details}${body}(file, ${scenario.line}))`
}

function removeStale(dir: string, keep: Set<string>) {
  if (!fs.existsSync(dir)) return
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      removeStale(full, keep)
      if (!fs.readdirSync(full).length) fs.rmdirSync(full)
    } else if (entry.name.endsWith('.spec.js') && !keep.has(full) && isGenerated(full)) {
      fs.rmSync(full)
      fs.rmSync(`${full}.map`, { force: true })
    }
  }
}

// Only files Spec++ wrote are removed, whatever else is there.
const isGenerated = (file: string) => fs.readFileSync(file, 'utf8').startsWith(HEADER)

// ---------------------------------------------------------------- source maps

const BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

// A number as a source map writes it: base64 digits of five bits each, least
// significant first, with the sign in the lowest bit of the first.
function vlq(n: number): string {
  let rest = n < 0 ? (-n << 1) | 1 : n << 1
  let out = ''
  do {
    let digit = rest & 31
    rest >>>= 5
    if (rest) digit |= 32
    out += BASE64[digit]
  } while (rest)
  return out
}

// A version 3 source map, from each generated line that stands for
// a line of the source to the start of that line. Each mapped line has one
// segment: generated column 0, the only source, its line, column 0, each but
// the generated column relative to the segment before.
function sourceMap(source: string, lines: Lines): string {
  let previous = 0
  const mappings = lines.map(([, line]) => {
    if (line === undefined) return ''
    const segment = `A${vlq(0)}${vlq(line - 1 - previous)}${vlq(0)}`
    previous = line - 1
    return segment
  })
  return `${JSON.stringify({ version: 3, sources: [source], names: [], mappings: mappings.join(';') })}\n`
}
